### PR TITLE
OpenCV 3.0.0 - ready

### PR DESCRIPTION
**Pull request by madduci**
Updated the code base to latest OpenCV 3.0.0 alpha version and Qt 5.2.1 Framework. Qt Gui app crashes at launch, as in the original code provided by authors. 
Fixed also CMakeLists for enabling non-Apple generation of binaries.

### CODE REVIEW

**Comment by linas** [comment]
Oh, sorry, I see that you did make a pull request. I did not see this at first ... so ignore my comment above.

**Comment by madduci** [comment]
Hi

Don't worry, I just wanted to let you know the repository now builds with
OpenCV github master.
Regards

Michele
Am 08.11.2014 18:34 schrieb "Linas Vepstas" notifications@github.com:

**Comment by linas** [comment]
I merged changes very similar to this into https://github.com/iCogLabs/face-analysis-sdk/

I was not able to merge this, because it seems the original repo has been deleted!?

**Comment by madduci** [comment]
don't worry, I haven't received any reply since then and I've cleaned up all my repos last week.

I've thought there wasn't any activity anymore

**Pull request closed without merging**
